_format_version: "1.1"
services:
  - name: Product_Catalog_API
    protocol: http
    host: localhost
    port: 8000
    path: /
    plugins: []
    routes:
      - tags:          
          - deck-managed
        name: Product_Catalog_API-listCategories
        methods:
          - GET
        paths:
          - /v1/catalog/categories$
        strip_path: false
      - tags:          
          - deck-managed
        name: Product_Catalog_API-listProductsInCategory
        methods:
          - GET
        paths:
          - /v1/catalog/products$
        strip_path: false
      - tags:                    
          - deck-managed
        name: Product_Catalog_API-viewProduct
        methods:
          - GET
        paths:
          - /v1/catalog/products/(?<productId>[^\/]+)$
        strip_path: false
      - tags:                    
          - deck-managed
        name: Product_Catalog_API-listProductReviews
        methods:
          - GET
        paths:
          - /v1/catalog/reviews$
        strip_path: false
    tags:          
      - deck-managed
