---
name: Contract Test Workflow

on:
  push:
    branches: [master, main]
  workflow_dispatch:

env:
  run_number: ${GITHUB_RUN_NUMBER}

permissions:
  checks: write

jobs:
  acceptance-stage-tests:
    name: Run acceptance stage tests
    runs-on: self-hosted
    steps:
      # Retreive latest spec from github
      # - name: "Setup artifact repository CLI (Jfrog CLI)"
      #   uses: jfrog/setup-jfrog-cli@v2
      #   env:
      #     JF_ENV_1: ${{ secrets.JF_SECRET }}
      # - name: "Download latest artifact (Jfrog Artifactory)"
      #   run: |
      #       jf rt ping
      #       jf rt download "default-api-generic-local/com.acmeps/product-catalog-api/" --sort-by=created --sort-order=desc --limit=1

      - name: Check out config repo to config-dir
        uses: actions/checkout@v3
        with:
          path: config-dir

      - name: Check out api repo to api-dir
        uses: actions/checkout@v3
        with:
          repository: ikenna/acme-pet-supplies
          path: api-dir

      - name: Ensure no changes applied outside of this repo
        run: |
          cd config-dir
          tree
          deck diff --non-zero-exit-code

      - name: Apply changes to API gateway
        run: |
          cd config-dir
          deck sync

      - name: Start upstream service and Prism validation proxy
        run: |
          cd api-dir
          ./upstream-mock-start.sh
          ./validation-proxy-start.sh
          
      - name: Install Portman if it is not installed
        run: |
          npm list @apideck/portman || npm install -g @apideck/portman

      - name: Generate and run API contract tests
        run: |
          cd api-dir
          rm -rf test-reports
          mkdir test-reports
          ./contract-tests-start.sh
          ./variation-tests-start.sh
          ./combined-tests-start.sh
          
      - name: "Upload test report as Github artifact"
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: api-dir/test-reports
